### ISSUE TITLE
[QUESTION] How to determine the value of `rss.worker.flush.queue.capacity`？

### ISSUE THREAD

**Issue by xunxunmimi5577** [alibaba/RemoteShuffleService#102]

**Comment by FMX** [comment]
@xunxunmimi5577 
The value `rss.worker.flush.queue.capacity` is calculated by the worker`s direct memory size.
```math
rss.worker.flush.queue.capacity = (worker direct memory size)/(rss.worker.flush.buffer.size)/2/(worker's disk count)
```

The worker's flush queue is designed to hold shuffle data to merge write requests.

**Comment by xunxunmimi5577** [comment]
ok，Thank you
