### ISSUE TITLE
[QUESTION] Executor在shuffle write/read 过程中是否落本地盘？

### ISSUE THREAD

**Issue by fuhaiq** [alibaba/RemoteShuffleService#107]
请教下：

- 在shuffle write时，executor直接将shuffle数据传至rss？还是落本地盘后再传？
- 在shuffle read时，executor从rss获取数据后，直接算？还是先落本地盘后再算？

我们每个节点就一块盘，且性能很差，如果shuffle阶段存在落盘，会导致大量随机I/O

/cc @who-need-to-know

/assign @who-can-solve-this-bug

**Comment by FMX** [comment]
@fuhaiq 
你好，针对你问到的两个问题，
第一个问题：shuffle write 过程中，executor 会直接将数据传到 rss ，不会落盘。
第二个问题：shuffle read 过程中，executor 会将直接从 rss 中取数据，不会落盘。
请注意，尽管shuffle read 或者 writer 过程是不会落盘的，但是在 executor 处理的数据过多发生 spill 的时候，executor 还是会写本地磁盘。
其次，在触发 rdd persist 的时候，如果配置为 DISK ，也会写本地盘。

**Comment by fuhaiq** [comment]
> @fuhaiq 你好，针对你问到的两个问题， 第一个问题：shuffle write 过程中，executor 会直接将数据传到 rss ，不会落盘。 第二个问题：shuffle read 过程中，executor 会将直接从 rss 中取数据，不会落盘。 请注意，尽管shuffle read 或者 writer 过程是不会落盘的，但是在 executor 处理的数据过多发生 spill 的时候，executor 还是会写本地磁盘。 其次，在触发 rdd persist 的时候，如果配置为 DISK ，也会写本地盘。

非常感谢～理解了。您说的 “但是在 executor 处理的数据过多发生 spill 的时候，executor 还是会写本地磁盘” 比如有聚合、排序操作时，数据量大时需要spill到本地磁盘进行外部排序吧？比如 ExternalSorter 的行为

**Comment by waitinfuture** [comment]
> > @fuhaiq 你好，针对你问到的两个问题， 第一个问题：shuffle write 过程中，executor 会直接将数据传到 rss ，不会落盘。 第二个问题：shuffle read 过程中，executor 会将直接从 rss 中取数据，不会落盘。 请注意，尽管shuffle read 或者 writer 过程是不会落盘的，但是在 executor 处理的数据过多发生 spill 的时候，executor 还是会写本地磁盘。 其次，在触发 rdd persist 的时候，如果配置为 DISK ，也会写本地盘。
> 
> 非常感谢～理解了。您说的 “但是在 executor 处理的数据过多发生 spill 的时候，executor 还是会写本地磁盘” 比如有聚合、排序操作时，数据量大时需要spill到本地磁盘进行外部排序吧？比如 ExternalSorter 的行为

对的，主要是排序，不管是sort算子还是sortagg的sort过程

**Comment by fuhaiq** [comment]
非常感谢～！理解了
