### ISSUE TITLE
[BUG] compile error

### ISSUE THREAD

**Issue by leoyy0316** [alibaba/RemoteShuffleService#109]
when i complie rss use [mvn install -DskipTests -Dcheckstyle.skip=true -Dscalastyle.skip=true  -Pspark-2 -Plog4j-1]
occur this error:
{[ERROR] D:\code\RemoteShuffleService\client\src\main\java\com\aliyun\emr\rss\client\write\LifecycleManager.scala:31: error: object netty is not a member of package io
[ERROR] import io.netty.util.internal.ConcurrentSet
[ERROR]           ^
[ERROR] D:\code\RemoteShuffleService\client\src\main\java\com\aliyun\emr\rss\client\write\LifecycleManager.scala:52: error: not found: type ConcurrentSet
[ERROR]   private val registeredShuffle = new ConcurrentSet[Int]()
[ERROR]                                       ^
[ERROR] D:\code\RemoteShuffleService\client\src\main\java\com\aliyun\emr\rss\client\write\LifecycleManager.scala:56: error: not found: type ConcurrentSet
[ERROR]   private val dataLostShuffleSet = new ConcurrentSet[Int]()
[ERROR]                                        ^
[ERROR] D:\code\RemoteShuffleService\client\src\main\java\com\aliyun\emr\rss\client\write\LifecycleManager.scala:57: error: not found: type ConcurrentSet
[ERROR]   private val stageEndShuffleSet = new ConcurrentSet[Int]()}

what should i do?

**Comment by FMX** [comment]
@leoyy0316
Hello. I think we had solved this problem on gitter.

**Comment by FMX** [comment]
<img width="1085" alt="540DDD97-CF84-4BCB-93D1-D4F975D4CB0D" src="https://user-images.githubusercontent.com/4150993/168212469-72ace46c-dd57-465e-a248-aacb6275bc6d.png">

If anyone found this issue, try to avoid using maven 3.8.5.
