### ISSUE TITLE
[BUG] Master‘s metrics of WorkerSlotsCount / WorkerSlotsUsed/  OverloadWorkerCount not update

### ISSUE THREAD

**Issue by AngersZhuuuu** [alibaba/RemoteShuffleService#120]
### How to reproduce the bug?
Steps to reproduce the bug.

### Could you share logs or screenshots?
If applicable, add logs/screenshots to help explain your problem.

/cc @who-need-to-know

/assign @who-can-solve-this-bug

**Comment by FMX** [comment]
Thank @AngersZhuuuu for fixing this.  #121
