### ISSUE TITLE
[QUESTION] net.jpountz.lz4.LZ4Exception: Error decoding offset 219424 of input buffer

### ISSUE THREAD

**Issue by xunxunmimi5577** [alibaba/RemoteShuffleService#138]

**Comment by xunxunmimi5577** [comment]
请问怎么解决这个错误？

**Comment by xunxunmimi5577** [comment]
我的配置
Spark
`spark.shuffle.manager org.apache.spark.shuffle.rss.RssShuffleManager
# must use kryo serializer because java serializer do not support relocation
spark.serializer org.apache.spark.serializer.KryoSerializer

spark.rss.ha.master.hosts xxx
spark.shuffle.service.enabled false

# optional:hash,sort
spark.rss.shuffle.writer.mode hash

# we recommend set spark.rss.push.data.replicate to true to enable server-side data replication
spark.rss.push.data.replicate false

# Note: RSS didn`t support Spark AQE now, but we`ll support it soon.
spark.sql.adaptive.enabled false
spark.sql.adaptive.localShuffleReader.enabled false
spark.sql.adaptive.skewJoin.enabled false

spark.rss.push.data.buffer.size 4m
spark.rss.push.data.maxReqsInFlight 98300
spark.rss.push.data.replicate false
spark.rss.push.data.queue.capacity 128`

env
`RSS_MASTER_MEMORY=2g
RSS_WORKER_MEMORY=4g
RSS_WORKER_OFFHEAP_MEMORY=32g
RSS_WORKER_JAVA_OPTS="-XX:-PrintGC -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintGCDateStamps -Xloggc:gc-worker.out -Dio.netty.leakDetectionLevel=advanced"
RSS_MASTER_JAVA_OPTS="-XX:-PrintGC -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintGCDateStamps -Xloggc:gc-master.out -Dio.netty.leakDetectionLevel=advanced"
RSS_PID_DIR="$RSS_HOME/pids"
RSS_LOG_DIR="$RSS_HOME/logs"`

master&worker
`rss.metrics.system.enabled true
rss.worker.flush.buffer.size 5m
rss.worker.flush.queue.capacity 4096
rss.worker.base.dirs /mnt/disk1/,/mnt/disk2


rss.master.port 9097
rss.ha.enabled true
rss.ha.service.id dev-cluster
rss.ha.nodes.dev-cluster node1,node2,node3

rss.ha.address.dev-cluster.node1 host1
rss.ha.address.dev-cluster.node2 host2
rss.ha.address.dev-cluster.node3 host3

rss.ha.port 9872
rss.ha.master.hosts host1,host2,host3


rss.rpc.io.mode NIO
rss.rpc.io.clientThreads 8
rss.rpc.io.serverThreads 8
rss.rpc.io.numConnectionsPerPeer 8

rss.push.data.maxReqsInFlight 98300
rss.push.data.buffer.size 4m
rss.push.data.queue.capacity 128`

**Comment by waitinfuture** [comment]
正在尝试复现

**Comment by FMX** [comment]
@xunxunmimi5577 
我认为你需要需要修改一下你的配置，rss.push.data.buffer.size 4m 这对于绝大多数任务来说，都太大了。默认值是 64KB。
这个配置是 一个 map task 对于 所有 reduce task 预先申请的内存大小，如果一个 stage 有  200 map task ，200 reduce ，64 M 的配置下，一个 map task 会需要 800 MB 堆内内存。
rss.push.data.maxReqsInFlight 这个选项回归默认值就好。

**Comment by FMX** [comment]
@xunxunmimi5577   出现问题的 rss 的 commit id 是什么？

**Comment by FMX** [comment]
@xunxunmimi5577 
https://gitter.im/RemoteShuffleServiceCommunity/Issue-138

方便的话，可以用上面这个 IM 直接联系

**Comment by FMX** [comment]
I think we have solved this problem. I'll close this issue. 
Reopen if you encounter any related problems. @xunxunmimi5577
