### ISSUE TITLE
when push big UnsafeRow,  throw an error : net.jpountz.lz4.LZ4Exception: Error decoding offset XXXX of input buffer

### ISSUE THREAD

**Issue by 942011334** [alibaba/RemoteShuffleService#174]
<img width="980" alt="企业微信截图_3f7a42a7-4593-4990-b997-1d3b13de8fe7" src="https://user-images.githubusercontent.com/26920583/176085235-0512706f-d6da-4968-aa0e-2ad01dd64191.png">

when push a big  UnsafeRow  to worker , then reduces fetch and decompress the big unsaferow,   throw an error : net.jpountz.lz4.LZ4Exception: Error decoding offset XXXX of input buffer

INFO HashBasedShuffleWriter: Push giant record, size 101248036.

![image](https://user-images.githubusercontent.com/26920583/176085304-398593e2-62a6-4bd0-acd4-c7e9b86c3b36.png)

we use default settings，the following show:
rss.push.data.buffer.size 64k
rss.worker.flush.buffer.size 256K

**Comment by FMX** [comment]
This problem might be caused by chunk read mechanism.

**Comment by 942011334** [comment]
https://github.com/alibaba/RemoteShuffleService/pull/495
@FMX cc
