### ISSUE TITLE
[QUESTION] HA模式下，指定Master服务IP和端口的地方只能配置一个IP

### ISSUE THREAD

**Issue by CCweixiao** [alibaba/RemoteShuffleService#24]
HA模式下，指定Master服务IP和端口的地方只能配置一个IP
 如：启动worker时：
sh /opt/ali_rss/rss-1.0.0-bin-release/sbin/start-worker.sh rss://master-ip:9097
如果用类似如下命令则会报错：
sh /opt/ali_rss/rss-1.0.0-bin-release/sbin/start-worker.sh rss://master1-ip:9097,rss://master2-ip:9097,rss://master3-ip:9097

我想配置多个master IP该怎样配置呢，因为，如果某一个master进程挂掉，脚本是无法运行成功的

**Comment by FMX** [comment]
HA 模式下，启动是不需要 rss://master-ip:9097 的。因为配置文件里面已经写了所有的地址。
@CCweixiao

**Comment by CCweixiao** [comment]
Spark作业中呢，地址spark.rss.master.address好像这里也只能配置一个

**Comment by CCweixiao** [comment]
> HA 模式下，启动是不需要 rss://master-ip:9097 的。因为配置文件里面已经写了所有的地址。 @CCweixiao

嗯嗯 已经尝试，可以啦

**Comment by FMX** [comment]
> Spark作业中呢，地址spark.rss.master.address好像这里也只能配置一个

这里会考虑变成支持配置多个节点的形式，只能配置一个确实存在节点宕机后不能使用的问题。

**Comment by waitinfuture** [comment]
> 

这里确实可以改进， 开个issue吧 @FMX

**Comment by FMX** [comment]
#26

**Comment by CCweixiao** [comment]
> #26

收到 感谢感谢

**Comment by wangshengjie123** [comment]
@CCweixiao hello，我提交了个pr，初步解决了这个问题，可以试试。

其实，我们最开始的的想法是：
1、引导大家区别配置Ha和non-ha的配置(虽然修复了客户端可以指定rss.master.address多个节点)
2、启动时，尽量使用rss-default.conf来解决问题

例如ha场景下：
     客户端配置：
        spark.rss.ha.master.hosts master1,master2,master3
        spark.rss.master.port 9097
     服务端配置：
         rss.ha.master.hosts master1,master2,master3
        spark.rss.master.port 9097
non-ha场景下：
     客户端配置：
        spark.rss.master.address master:9097
     服务端配置：
         rss.master.address master:9097

这样我们启动master时就不用使用 sh start-master.sh rss://master1:9097[,rss://master2:9097]

**Comment by CCweixiao** [comment]
感谢您的回复

目前我们master的配置就是这样的，
rss.ha.master.hosts master1,master2,master3
spark.rss.master.port 9097
启动master时没有指定master的地址，
只是，客户端之前只能指定一个master的IP和端口

**Comment by wangshengjie123** [comment]
> 感谢您的回复
> 
> 目前我们master的配置就是这样的， rss.ha.master.hosts master1,master2,master3 spark.rss.master.port 9097 启动master时没有指定master的地址， 只是，客户端之前只能指定一个master的IP和端口

不好意思，回复有些迟，之前的服务端配置有些错误，spark.rss.master.port 9097，spark前缀印象中可以去掉。
咱们客户端也可以配置多个host，只是目前只能统一一个port，配置加个spark.前缀就好
