### ISSUE TITLE
[FEATURE] Support zstd compression

### ISSUE THREAD

**Issue by pan3793** [alibaba/RemoteShuffleService#312]
### Is your feature request related to a problem? Please describe.

Zstd is a modern compression algorithm w/ good trade-off between compression ratio and speed. In our testing, the zstd-jni:1.5.2 (level 1) could achieve the same speed and ~2x compression ratio comparing to lz4 in Spark shuffle scenario.

### Describe the solution you'd like

Implementing a zstd version of `RssLz4Trait`, some refactoring is needed.

### Describe alternatives you've considered

Use `org.apache.spark.io.CompressionCodec`, which is adopted by Spark build-in shuffle, is much much solid.

/cc @who-need-to-know

/assign @who-can-help-you

**Comment by liugs0213** [comment]
I wonder if the performance will be reduced much after using ZSTD compression. It seems to be friendly to network IO and disk size.

**Comment by pan3793** [comment]
@liugs0213 I described the performance in the PR description.

> In our testing, the zstd-jni:1.5.2 (level 1) could achieve the same speed ...

**Comment by AngersZhuuuu** [comment]
@waitinfuture Can close this
