### ISSUE TITLE
[FEATURE] Extract Partition's  file name/length/ChunkOffset  FileMeta trait from FileWriter

### ISSUE THREAD

**Issue by AngersZhuuuu** [alibaba/RemoteShuffleService#323]
### Describe alternatives you've considered

/cc @who-need-to-know

/assign @who-can-help-you

**Comment by pan3793** [comment]
For KV store, Rocksdb is a more future-proof option than LevelDB, specifically, LevelDB does not work on macOS but RocksDB does(see [SPARK-35782](https://issues.apache.org/jira/browse/SPARK-35782))
