### ISSUE TITLE
[Question] Fail to build project 

### ISSUE THREAD

**Issue by magicsilence** [alibaba/RemoteShuffleService#36]
Get a error when build project as follows 
`
./dev/make-distribution.sh -Pspark-3 -Dspark.version=3.0.1 -Dmaven.test.skip=true
`

error message  :
`
[INFO] Aliyun E-MapReduce Shuffle Service Project Parent POM SUCCESS [  0.344 s]
[INFO] Aliyun E-MapReduce Shuffle Service Common .......... SUCCESS [ 16.039 s]
[INFO] Aliyun E-MapReduce Shuffle Service Java Client ..... SUCCESS [ 14.089 s]
[INFO] Aliyun E-MapReduce Shuffle Service Shuffle Manager for Spark FAILURE [  1.814 s]
[INFO] Aliyun E-MapReduce Shuffle Service Shuffle Manager for Spark SKIPPED
[INFO] Aliyun E-MapReduce Shuffle Service Common .......... SUCCESS [ 13.077 s]
[INFO] Aliyun E-MapReduce Shuffle Service Service Master Module SKIPPED
[INFO] Aliyun E-MapReduce Shuffle Service Service Worker Module SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  32.997 s (Wall Clock)
[INFO] Finished at: 2022-01-17T14:14:59+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project shuffle-manager-common: Could not resolve dependencies for project com.aliyun.emr:shuffle-manager-common:jar:1.0.0: Could not find artifact com.aliyun.emr:client:jar:tests:1.0.0 in  XXXX  -> [Help 1]
[ERROR] 
`

**Comment by waitinfuture** [comment]
Hi @magicsilence , as the doc says currently RSS supports Spark version higher than 3.1.0, I suggest to upgrade your spark version since there have been a lot improvement in Spark3.2.0. If it's hard to upgrade spark version, we will consider whether to support 3.0.

**Comment by waitinfuture** [comment]
> @waitinfuture I found it meet error when the build cmd add ` -Dmaven.test.skip=true` . Back to normal when remove it.

RSS supports spark3.0 now
