### ISSUE TITLE
[QUESTION] 采用 HA 部署时，对主节点个数有要求么？

### ISSUE THREAD

**Issue by fuhaiq** [alibaba/RemoteShuffleService#448]
在讨论区提了下，没人回复，只好丢在 issue 里面了

https://github.com/alibaba/RemoteShuffleService/discussions/395

---

我看到 HA 模式下，例子配置了3个主节点，个数有要求么？

有建议么？比如最少3个，奇数个？2个可以么？

**Comment by waitinfuture** [comment]
至少3个，奇数。我们对discussions区确实关注不太够😭
