### ISSUE TITLE
[BUG] Filechannel close takes a long time.

### ISSUE THREAD

**Issue by packageman** [alibaba/RemoteShuffleService#50]
### What is the bug?
When committing files, channel.close() sometimes takes a long time.

### How to reproduce the bug?

- shuffle write data size: 14.5G
- shuffle partition num: 200

![image](https://user-images.githubusercontent.com/12949466/151497792-8f117f93-f496-4afd-9f9d-61171933e118.png)

sparkProperties:

```
spark.executor.instances: 5
spark.kubernetes.executor.request.cores: 6
spark.executor.memory: 30g
spark.shuffle.manager: org.apache.spark.shuffle.rss.RssShuffleManager
spark.rss.master.address: 192.168.x.xx:9097
spark.shuffle.service.enabled: false
spark.rss.push.data.replicate: false
spark.sql.adaptive.enabled: false
spark.sql.adaptive.localShuffleReader.enabled: false
spark.sql.adaptive.skewJoin.enabled: false
```

rss-defaults.conf

```
rss.master.address 192.168.5.19:9097
rss.metrics.system.enable true
rss.remove.shuffle.delay 300s
rss.worker.flush.buffer.size 256k
rss.worker.flush.queue.capacity 512
rss.worker.base.dirs /mnt/disk1
```

ECS as virtual macheine:

16c64g(ecs.g7.4xlarge) x 3 workers, each worker has ESSD 100G PL1 disk.

### Could you share logs or screenshots?

The first read took 28s because it was waiting for the completion of the previous stage commit file, and the subsequent shuffle read took a short time (within 0.1s), and the commit file was slow because it was slow when executing [`channel.close()`](https://github.com/alibaba/RemoteShuffleService/blob/main/server-worker/src/main/java/com/aliyun/emr/rss/service/deploy/worker/FileWriter.java#L229).

![image](https://user-images.githubusercontent.com/12949466/151498308-0f5d9a74-e282-4bea-9b20-8e8da6c05ebc.png)

When I changed [`FileChannel.write()`](https://github.com/alibaba/RemoteShuffleService/blob/main/server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/LocalStorageManager.scala#L75) to `DataOutputStream.write()`, the above problem disappeared.

![image](https://user-images.githubusercontent.com/12949466/151498504-2bcaa887-1b51-4c3c-86f3-7e4490754fdf.png)

Note: I added `channel.force()` methoed before `channel.close()` and found that the time-consuming is mainly caused by `channel.force()`.

**Comment by FMX** [comment]
Hi, can you share your disk metrics like disk bandwidth or "%iowait" data?
I think this means you need more disks, can you try to add more disks to "rss.worker.base.dirs" ? 
@packageman

**Comment by packageman** [comment]
The IO metrics command I am using is `iostat -x 2`

- IO metrics when writing files using FileChannel(ESSD 100G PL1 disk):
    
    ![image](https://user-images.githubusercontent.com/12949466/152946820-500e717b-531f-4c38-8fbd-b9799813d4f1.png)

- IO metrics when writing files using DataOutputStream(ESSD 100G PL1 disk):

    ![image](https://user-images.githubusercontent.com/12949466/152947418-c961f7ad-08a8-4ca7-9f48-96c322bc1960.png)

When using FileChannel, `%iowait` is almost 100%, and when using DataOutputStream, only 32% max, and it takes less time to complete the writing of DataOutputStream.

I upgraded the disk to ESSD 500G PL2 and re-tested the FileChannel, and the IO metrics are as follows:

![image](https://user-images.githubusercontent.com/12949466/152951036-3a532bee-c257-419c-b56c-4d75d3497a08.png)

`%iowait` has dropped to about %20, `w/s` and `wKB/s` have been improved, and the writing time has been shortened a lot.

Through the above tests, it is found that the writing speed can be improved by improving disk performance or changing FileChannel to DataOutputStream(which may bring additional CPU and memory overhead for data copying).

**Comment by FMX** [comment]
Thanks for your concentration. You are always welcome to discuss your idea here.

I think you might misunderstand the meaning of %iowait.
IOWait (usually labeled %wa in top) is a sub-category of idle (%idle is usually expressed as all idle except defined subcategories), meaning the CPU is not doing anything. Therefore, as long as there is another process that the CPU could be processing, it will do so. Additionally, idle, user, system, iowait, etc are measurements for the CPU. In other words, you can think of iowait as the idle caused by waiting for io.
So high iowait value means efficient CPU usage and, higher disk performance means lower iowait.

FileChannel vs DataOutputStream, there is some existing reference.
http://web.archive.org/web/20120815094827/http://geekomatic.ch/2008/09.html
http://web.archive.org/web/20120815094827/http://geekomatic.ch/2008/09.html
