### ISSUE TITLE
[FEATURE] Remove the dependency on active shuffle for dynamic allocation for spark 3

### ISSUE THREAD

**Issue by packageman** [alibaba/RemoteShuffleService#53]
### Is your feature request related to a problem? Please describe.
Only enabling shuffle tracking for spark 3 to support dynamic allocation will cause the executor to shut down late while waiting for the active shuffle to be consumed. Because the shuffle data is stored in the remote shuffle service, this wait is unnecessary.
 

### Describe the solution you'd like
Add a spark patch like spark 2.x to support dynamic allocation.

**Comment by FMX** [comment]
This feature will need a little time.
