### ISSUE TITLE
[BUG] CompressionMethod and checksum are not consistent when zstd level is negative

### ISSUE THREAD

**Issue by nafiyAix** [alibaba/RemoteShuffleService#551]
`[ERROR]   ClusterReadWriteTest.testMiniCluster:35->$anonfun$testMiniCluster$1$adapted:35->$anonfun$testMiniCluster$1:80 Checksum not equal! expected: -48877264, actual: 1814018951`

``` java
clientConf.set("rss.client.compression.zstd.level", "-1")
```
when zstd level less than 0, test failed. So do our product cluster.

_Originally posted by @zy-jordan in https://github.com/alibaba/RemoteShuffleService/pull/451#discussion_r962982555_

**Comment by zy-jordan** [comment]
I think it most likely goes wrong on bit operations when **compressedLength >= length**
for example
### compress
``` java
// compressMethod: 16(COMPRESSION_METHOD_RAW)
// compressionLevel: -1
compressedBuffer[MAGIC_LENGTH] = (byte) (compressMethod | compressionLevel); // -1
```
### decompress
``` java
    int token = src[MAGIC_LENGTH] & 0xFF; // -1 & 0xFF : 255
    int compressionMethod = token & 0xF0; // 255 & 0xF0 : 240
```
In fact, the right _compressMethod_ is 16(COMPRESSION_METHOD_RAW) rather than ~~240~~

**Comment by nafiyAix** [comment]
Yes it is, I think it may be because the level is a negative number, then when calculating the token, its result will not be the same as the result of using a non-negative number level whose high bit corresponds to the compression method and the low bit corresponds to the compressor level. Maybe we can do some transformation on it to make it be a positive integer that won't collide with other level.
