### ISSUE TITLE
[BUG] v0.1.2 compile faild

### ISSUE THREAD

**Issue by thomasg19930417** [alibaba/RemoteShuffleService#556]
using command  ./dev/make-distribution.sh  -Pspark-3.2
![image](https://user-images.githubusercontent.com/20243868/188558776-ace6138b-7dae-4fed-ae28-da2915112d7c.png)

./dev/make-distribution.sh  -Pspark-3
![image](https://user-images.githubusercontent.com/20243868/188558864-7651c0b0-1cda-44cb-9cce-d6fbd2793afc.png)

**Comment by waitinfuture** [comment]
ping @FMX

**Comment by FMX** [comment]
@thomasg19930417  branch-0.1 needs log4j profile.

**Comment by FMX** [comment]
Using "./dev/make-distribution.sh  -Pspark-3.2,log4j-1" or  "./dev/make-distribution.sh  -Pspark-3.2,log4j-2".

**Comment by thomasg19930417** [comment]
> Using "./dev/make-distribution.sh -Pspark-3.2,log4j-1" or "./dev/make-distribution.sh -Pspark-3.2,log4j-2".
这里貌似只能指定到spark3版本，无法区分 3.2 、3.3.
![image](https://user-images.githubusercontent.com/20243868/188569150-495466f1-ceb7-489a-b764-1c50d04ca3a1.png)
修改pom spark-3 profile中spark 版本到3.2后编译报错
![image](https://user-images.githubusercontent.com/20243868/188569604-f72c2cd0-2937-4844-8092-9ce4b82369a3.png)

**Comment by thomasg19930417** [comment]
3.2中getreader代码
![image](https://user-images.githubusercontent.com/20243868/188590832-df9efd0d-579a-4ee2-9601-dc3c04528174.png)
根据这个是不是直接把子类的这个实现去除就可以了
 def getReader[K, C](
      handle: ShuffleHandle,
      startPartition: Int,
      endPartition: Int,
      context: TaskContext,
      metrics: ShuffleReadMetricsReporter): ShuffleReader[K, C] = {
    handle match {

**Comment by waitinfuture** [comment]
```
Build for Spark 2
./dev/make-distribution.sh -Pspark-2 -Plog4j-1/-Plog4j-2

Build for Spark 3
./dev/make-distribution.sh -Pspark-3 -Plog4j-1/-Plog4j-2
```
v0.1.2不需要指定具体的spark版本，直接指定spark-3就可以了，参考这个分支的README。main分支支持指定具体spark版本

**Comment by thomasg19930417** [comment]
> ```
> Build for Spark 2
> ./dev/make-distribution.sh -Pspark-2 -Plog4j-1/-Plog4j-2
> 
> Build for Spark 3
> ./dev/make-distribution.sh -Pspark-3 -Plog4j-1/-Plog4j-2
> ```
> 
> v0.1.2不需要指定具体的spark版本，直接指定spark-3就可以了，参考这个分支的README。main分支支持指定具体spark版本

好的 多谢
