### ISSUE TITLE
[Feature] Support k8s.

### ISSUE THREAD

**Issue by fishcus** [alibaba/RemoteShuffleService#66]
Any plans to support run on K8s？

**Comment by FMX** [comment]
RSS can run on K8S now if you write your own K8S pods attached with storage.

**Comment by fishcus** [comment]
> RSS can run on K8S now if you write your own K8S pods attached with storage.
yeah,  it works with some extra work, and what i really want to know is when will you release an official version

**Comment by FMX** [comment]
@fishcus 
We had a plan to support the K8S operator. The official K8S support will be announced in this authum or earlier. So you have to wait a couple of months.
You are welcome to contribute this feature if you want.
