### ISSUE TITLE
[BUG] duplicated tcp_nodelay flag

### ISSUE THREAD

**Issue by lichaojacobs** [alibaba/RemoteShuffleService#68]
### What is the bug?
there is duplicated tcp_nodelay flag set by sever side
![image](https://user-images.githubusercontent.com/7459785/157251686-3d2e6b19-f0c8-48f3-a5b8-086dfbae130f.png)

### How to reproduce the bug?
Steps to reproduce the bug.

### Could you share logs or screenshots?
If applicable, add logs/screenshots to help explain your problem.

/cc @who-need-to-know

/assign @who-can-solve-this-bug

**Comment by FMX** [comment]
Thanks. Merged.
