### ISSUE TITLE
[REFACTOR] Convert pbRegisterWorker from method to case class

### ISSUE THREAD

**Issue by nafiyAix** [alibaba/RemoteShuffleService#694]
### Describe the intention you'd like
Convert 
```
def pbRegisterWorker(
      host: String,
      rpcPort: Int,
      pushPort: Int,
      fetchPort: Int,
      replicatePort: Int,
      disks: Map[String, DiskInfo],
      userResourceUsage: Map[UserIdentifier, ResourceConsumption],
      requestId: String): PbRegisterWorker = {
```
to be a case class like other RPC request

/cc @who-need-to-know

/assign @who-can-help-you

**Comment by pan3793** [comment]
It's by design, see https://github.com/alibaba/RemoteShuffleService/issues/673

**Comment by nafiyAix** [comment]
@pan3793 Thanks. I see this method is under ControlMessage and PbRegisterWorker belongs to the TransportMessages.proto, so i'm a bit confused about do we need to close this issue or continue to refactor it?

**Comment by pan3793** [comment]
The overall goal is to remove ControlMessage, for implementation, please send PR if you have a better idea.

**Comment by nafiyAix** [comment]
Oh i see, will close it
