### ISSUE TITLE
[BUG] Offer Slot Issue

### ISSUE THREAD

**Issue by kettlelinna** [alibaba/RemoteShuffleService#92]
### What is the bug?
master log appear Offer slots for 1 reducer of application, and I review the code found it seems worker not normal,
but I can't get log from woker log file

### How to reproduce the bug?
I am not sure how to trigger it
this is my conf
for rss-default.conf
rss.master.address 192.168.xx.xx:9097
rss.metrics.system.enable true
rss.remove.shuffle.delay 300s
rss.worker.flush.buffer.size 256k
rss.worker.flush.queue.capacity 512
rss.worker.base.dirs /tmp/clm/rss

for client:
spark.shuffle.manager org.apache.spark.shuffle.rss.RssShuffleManager
spark.serializer org.apache.spark.serializer.KryoSerializer
spark.rss.master.address rss-master-host:9097
spark.shuffle.service.enabled false
spark.rss.shuffle.writer.mode hash
spark.rss.push.data.replicate true
spark.sql.adaptive.localShuffleReader.enabled false
spark.sql.adaptive.enabled true
spark.sql.adaptive.skewJoin.enabled true 

btw, when I setup spark.rss.push.data.replicate=false
it can run and just need few mins to be finish but the result is 0 

### Could you share logs or screenshots?
If applicable, add logs/screenshots to help explain your problem.
![693023cf710f5bd37510a9d32df80be](https://user-images.githubusercontent.com/58110598/162528946-e616b09f-6799-46dc-b119-e5c2278adcb0.jpg)

/cc @who-need-to-know

/assign @who-can-solve-this-bug

**Comment by FMX** [comment]
@kettlelinna Hi, thanks for your reply.
Can you share your spark version and RSS commit hash?
And how many RSS workers do you have?

**Comment by kettlelinna** [comment]
Hi @FMX, 
the spark version is 3.1.1
the commit hash is `2ea136f`
only one works and one master for RSS now

**Comment by FMX** [comment]
@kettlelinna If you have only one worker. 
You should set spark.rss.push.data.replicate to false.
Replication will require at least two workers.
